version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install -r requirements.txt
            python -m pip install -e .
      - run:
          name:  Run tests in same venv
          command: |
            . venv/bin/activate
            python -m flake8 --statistics
            python -m pytest -v --cov .
