version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -e .
      - save_cache: # ** special step to save dependency cache **
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name:  Run tests in same venv
          command: |
            . venv/bin/activate
            flake8 --statistics
            pytest -v
            coverage run -m pytest

